# fly.toml app configuration file generated for videorender-ncmuoa on 2025-07-04T23:50:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'videorender-ncmuoa'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 8192
