# fly.toml app configuration file generated for videorender on 2025-07-04T12:51:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "videorender-skivdg"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5m"

[build]

[env]
NODE_ENV = "production"
PORT = "8080"
SESSION_SECRET = "your-super-secret-32-character-session-key-here-change-this"
MAX_CONCURRENT_JOBS = "3"
VIDEO_DURATION_SECONDS = "600"
CLEANUP_TEMP_FILES = "true"
TEMP_DIR = "/app/temp"
OUTPUT_DIR = "/app/output"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "suspend"
  min_machines_running = 0
  machine_idle_timeout = "35m"
  processes = ["app"]

[[vm]]
  memory = "8gb"
  cpu_kind = "shared"
  cpus = 8
  memory_mb = 8192

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[processes]
  app = "npm start"
