# fly.toml app configuration file generated for videorender on 2025-07-04T12:51:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "videorender-skivdg"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "8gb"
  cpu_kind = "shared"
  cpus = 8
  memory_mb = 8192
